#ifndef _SCENE_H_
#define _SCENE_H_

// Ignore warnings generated by using a GUID with std::map.
#pragma warning(disable: 4786)

#include <map>
#include <d3d8.h>
#include <d3dx8.h>
#include "Camera.h"
#include "Common.h"
#include "Gizmo.h"
#include "Grid.h"
#include "Model.h"

class CScene
{
public:
  CScene();
  ~CScene();
  BOOL Create(HWND handle);
  void Render();
  void Resize();
  void Move(POINT, POINT, float);
  void OnMouseWheel(short zDelta);
  void CScene::OnImportModel();
  void Pick(POINT mousePoint);
  void ReleaseResources();
  void CheckInput(float);
  void ScreenRaycast(POINT screenPoint,
    D3DXVECTOR3 *origin, D3DXVECTOR3 *dir);
  
private:
  HWND m_hWnd;
  CGizmo m_gizmo;
  CCamera m_camera;
  IDirect3DDevice8* m_device;
  IDirect3D8* m_d3d8;
  D3DPRESENT_PARAMETERS m_d3dpp;
  std::map<GUID, CModel> m_models;
  CGrid m_grid;
  GUID m_selectedModelId;
};

#endif